[package]
name = "ui"
version = "0.0.0"
edition = "2021"
description = "The UI for steam random"


[dependencies]
api.workspace=true
db.workspace = true
goals_lib.workspace = true
tokio.workspace = true
eframe.workspace = true

[[bin]]
path = "src/main.rs"
name = "steam-rand-ui"
